logging:
    level:
        org:
            hibernate:
                SQL: debug
spring:
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/cdss?createDatabaseIfNotExist=true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    flyway:
        locations: classpath:/db/migrations